accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView
from config.settings import LOGOUT_REDIRECT_URL
from .views import (
    signIn,
    signUp,
    logout
)

app_name = "accounts"


urlpatterns = [
    path("",signIn,name="signIn"),
    path("signUp/",signUp,name="signUp"),
    path('logout/', LogoutView.as_view(next_page=LOGOUT_REDIRECT_URL), name='logout'),
    
]

config/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
      path('', include("homepage.urls",namespace='homepage')),
    path('auth/',include('accounts.urls',namespace="accounts")),
]

if settings.DEBUG:
    urlpatterns = urlpatterns + \
        static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + \
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

homepage/urls.py
from os import name
from django.urls import path

app_name = "homepage"

from .views import (
    index,
    courses,
    raisec,
    courseDetails,
    recommendation,
    addGrade,
    contactPage
)

urlpatterns = [
    path('', index,name="homepage"),
    path('courses/',courses,name='courses'),
    path('raisec/',raisec,name="raisec"),
    path('course/details/<int:id>/',courseDetails,name="courseDetails"),
    path('recommendation/',recommendation,name="recommendation"),
    path('addGrade/',addGrade,name="addGrade"),
    path("contact/",contactPage,name="contact")
 
]

templates/base.html
<!doctype html>
<html class="no-js" lang="zxx">

{% include 'head.html' %}
   <body>
     {% include 'preloader.html' %}
     {% include 'header.html' %}

     {% block content %}{% endblock content %}

    
   {% include 'footer.html' %}


   </body>
</html>

templates/footer.html
{% load static %}

<footer class="footer-wrapper footer-layout1">
    <div class="widget-area">
       <div class="container">
          <div class="row justify-content-between">
             <div class="col-md-6 col-xxl-3 col-xl-4">
                <div class="widget footer-widget">
                   <div class="as-widget-about">
                      <div class="about-logo"><a href="index.html"><img src="{% static  'assets/img/logo-white.svg' %}" alt="Acadu"></a></div>
                      <p class="about-text">Continually optimize backward manufactured products whereas communities negotiate life compelling alignments</p>
                      <h4 class="footer-info-title">Follow Us On:</h4>
                      <div class="as-social"><a href="https://www.facebook.com/"><i class="fab fa-facebook-f"></i></a> <a href="https://www.twitter.com/"><i class="fab fa-twitter"></i></a> <a href="https://www.linkedin.com/"><i class="fab fa-linkedin-in"></i></a> <a href="https://www.instagram.com/"><i class="fab fa-instagram"></i></a> <a href="https://www.youtube.com/"><i class="fab fa-youtube"></i></a></div>
                   </div>
                </div>
             </div>
             <div class="col-md-6 col-xl-auto">
                <div class="widget widget_nav_menu footer-widget">
                   <h3 class="widget_title">Quick link</h3>
                   <div class="menu-all-pages-container">
                      <ul class="menu">
                       <li><a href="index-2.html">Home</a></li>
                       <li><a href="course.html">Courses</a></li>
                       <li><a href="sign-in.html">Sign In</a></li>
                      
                      </ul>
                   </div>
                </div>
             </div>
             <div class="col-md-6 col-xl-auto">
                <div class="widget widget_nav_menu footer-widget">
                   <h3 class="widget_title">More</h3>
                   <div class="menu-all-pages-container">
                      <ul class="menu">
              
                       <li><a href="sign-up.html">Sign Up</a></li>
                       <li><a href="raisec.html">Raisec</a></li>
                       <li><a href="contact.html">Contact</a></li>
                      </ul>
                   </div>
                </div>
             </div>
             <div class="col-md-6 col-xl-3">
                <div class="widget footer-widget">
                   <h3 class="widget_title">Get in touch!</h3>
                   <form class="newsletter-widget">
                      <p class="footer-text">Fusce varius, dolor tempor interdum tristiquei bibendum service life.</p>
                      <div class="form-group"><input class="form-control" type="email" placeholder="Enter Email" required=""> <i class="fal fa-envelope"></i></div>
                      <button type="submit" class="as-btn shadow-none">Subscribe</button>
                   </form>
                </div>
             </div>
          </div>
       </div>
    </div>
 
    <div class="shape-mockup jump d-none d-xl-block" data-top="24%" data-left="4%"><img src="{% static 'assets/img/shape/footer_shape_1.png' %}" alt="shapes"></div>
    <div class="shape-mockup jump-reverse d-none d-xl-block" data-bottom="20%" data-right="4%"><img src="{% static 'assets/img/shape/footer_shape_2.png' %}" alt="shapes"></div>
    <div class="shape-mockup" data-top="0" data-right="0"><img src="{% static 'assets/img/shape/footer_shape_3.png' %}" alt="shapes"></div>
 </footer>
  <script src="{% static 'assets/js/vendor/jquery-3.6.0.min.js' %}"></script><script src="{% static  'assets/js/app.min.js' %}"></script><script src="{% static 'assets/js/main.js' %}"></script>

templates/head.html
{% load static %}

<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>Acadu - Online Courses & Education HTML Template - Home Two</title>
    <meta name="author" content="Angfuzsoft">
    <meta name="description" content="Acadu - Online Courses & Education HTML Template">
    <meta name="keywords" content="Acadu - Online Courses & Education HTML Template">
    <meta name="robots" content="INDEX,FOLLOW">
    <meta name="viewport" content="width=device-width,initial-scale=1,shrink-to-fit=no">
    <link rel="apple-touch-icon" sizes="57x57" href="{% static 'assets/img/favicons/apple-icon-57x57.png' %}">
    <link rel="apple-touch-icon" sizes="60x60" href="{% static 'assets/img/favicons/apple-icon-60x60.png' %}">
    <link rel="apple-touch-icon" sizes="72x72" href="{% static 'assets/img/favicons/apple-icon-72x72.png' %}">
    <link rel="apple-touch-icon" sizes="76x76" href="{% static 'assets/img/favicons/apple-icon-76x76.png' %}">
    <link rel="apple-touch-icon" sizes="114x114" href="{% static 'assets/img/favicons/apple-icon-114x114.png' %}">
    <link rel="apple-touch-icon" sizes="120x120" href="{% static 'assets/img/favicons/apple-icon-120x120.png' %}">
    <link rel="apple-touch-icon" sizes="144x144" href="{% static 'assets/img/favicons/apple-icon-144x144.png' %}">
    <link rel="apple-touch-icon" sizes="152x152" href="{% static 'assets/img/favicons/apple-icon-152x152.png' %}">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'assets/img/favicons/apple-icon-180x180.png' %}">
    <link rel="icon" type="image/png" sizes="192x192" href="{% static 'assets/img/favicons/android-icon-192x192.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'assets/img/favicons/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="96x96" href="{% static 'assets/img/favicons/favicon-96x96.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'assets/img/favicons/favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'assets/img/favicons/manifest.json' %}">
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="msapplication-TileImage" content="{% static 'assets/img/favicons/ms-icon-144x144.png' %}">
    <meta name="theme-color" content="#ffffff">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Jost:wght@100;200;300;400;500;600;700;800;900&family=Roboto:wght@100;300;400;500;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'assets/css/app.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/fontawesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/style.css' %}">
 </head>

templates/header.html
      {% load static %}
      
      <div class="popup-search-box d-none d-lg-block">
        <button class="searchClose"><i class="fal fa-times"></i></button>
        <form action="#"><input type="text" placeholder="What are you looking for?"> <button type="submit"><i class="fal fa-search"></i></button></form>
     </div>
     
     <div class="as-menu-wrapper">
        <div class="as-menu-area text-center">
           <button class="as-menu-toggle"><i class="fal fa-times"></i></button>
           <div class="mobile-logo"><a href="index.html"><img src="{% static 'assets/img/logo.svg' %}" alt="Acadu"></a></div>
           <div class="as-mobile-menu">
              <ul>
                 <li class="menu-item-has-children">
                    <a href="{% url 'homepage:homepage' %}">Home</a>
                    
                 </li>
                 <li class="menu-item-has-children">
                    <a href="{% url 'homepage:courses' %}">Courses</a>
                 
                 </li>
                 <li class="menu-item-has-children">
                    <a href="#">Pages</a>
                    <ul class="sub-menu">
                       <li><a href="{%  url 'accounts:signIn' %}">Sign In</a></li>
                       <li><a href="{% url 'accounts:signUp' %}">Sign Up</a></li>
                       <li><a href="raisec.html">Raisec</a></li>
                    </ul>
                 </li>
           
               
                 <li><a href="{% url 'homepage:contact' %}">Contact</a></li>
              </ul>
           </div>
        </div>
     </div>
     <header class="as-header header-layout2">
      
        <div class="sticky-wrapper">
           <div class="sticky-active">
              <div class="menu-area">
                 <div class="container">
                    <div class="row align-items-center justify-content-between">
                       <div class="col-auto">
                          <div class="header-logo"><a href="index.html"><img src="{% static 'assets/img/logo.svg' %}" alt="Acadu"></a></div>
                       </div>
                       <div class="col-auto d-none d-xl-inline-block">
                          <div class="category-menu-wrap">
                             <a class="menu-expand" href="#"><i class="fa-solid fa-list"></i>Categories</a>
                             <nav class="category-menu">
                                <ul>
                                 {% if course_category %}


                                 {% for i in course_category %}
                                 <li><a href="course">{{i.category_name}}</a></li>
                                  
                                 {% endfor %}

                                 {% endif %}
                                  
                                </ul>
                             </nav>
                          </div>
                       </div>
                       <div class="col-auto">
                          <div class="row align-items-center">
                             <div class="col-auto">
                                <nav class="main-menu d-none d-lg-inline-block">
                                   <ul>
                                      <li class="menu-item-has-children">
                                         <a href="{% url 'homepage:homepage' %}">Home</a>
                                       
                                      </li>
                                      <li class="menu-item-has-children">
                                         <a href="{% url 'homepage:courses' %}">Courses</a>
                                         
                                      </li>
                               
                                      {% if request.user.is_authenticated %}
                                       
                                      {% else %}


                                      <li class="menu-item-has-children">
                                      
   
                                       <a href="#">Pages</a>
                                       <ul class="sub-menu">
                                        
                                          <li><a href="{% url 'accounts:signIn' %}">Sign In</a></li>
                                          <li><a href="{% url 'accounts:signUp' %}">Sign Up</a></li>
                                         
                                       
                                       </ul>
                                    </li>

                                    {% endif %}
                                 
                                      <li><a href="{% url 'homepage:contact' %}">Contact</a></li>
                                   </ul>
                                </nav>
                                <button type="button" class="as-menu-toggle d-inline-block d-lg-none"><i class="far fa-bars"></i></button>
                             </div>
                           
                          </div>
                       </div>
                    </div>
                 </div>
              </div>
           </div>
        </div>
     </header>

templates/preloader.html
{% load static %}

<div class="preloader">
    <button class="as-btn style3 preloaderCls">Cancel Preloader</button>
    <div class="preloader-inner"><span class="loader"></span></div>
 </div>
 