accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView
from config.settings import LOGOUT_REDIRECT_URL
from .views import (
    signIn,
    signUp,
    logout
)

app_name = "accounts"


urlpatterns = [
    path("",signIn,name="signIn"),
    path("signUp/",signUp,name="signUp"),
    path('logout/', LogoutView.as_view(next_page=LOGOUT_REDIRECT_URL), name='logout'),
    
]

config/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
      path('', include("homepage.urls",namespace='homepage')),
    path('auth/',include('accounts.urls',namespace="accounts")),
]

if settings.DEBUG:
    urlpatterns = urlpatterns + \
        static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + \
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

homepage/urls.py
from os import name
from django.urls import path

app_name = "homepage"

from .views import (
    index,
    courses,
    raisec,
    courseDetails,
    recommendation,
    addGrade,
    contactPage
)

urlpatterns = [
    path('', index,name="homepage"),
    path('courses/',courses,name='courses'),
    path('raisec/',raisec,name="raisec"),
    path('course/details/<int:id>/',courseDetails,name="courseDetails"),
    path('recommendation/',recommendation,name="recommendation"),
    path('addGrade/',addGrade,name="addGrade"),
    path("contact/",contactPage,name="contact")
 
]

homepage/models.py
from pyexpat import model
from django.db import models

# Create your models here.


class ContactInfor(models.Model):
    address = models.CharField(max_length = 255)
    phone_number = models.CharField(max_length = 255)
    open_hours = models.CharField(max_length = 255)


    def __str__(self) -> str:
        return self.address

class Subjects(models.Model):
    subject = models.CharField(max_length = 255)

    def __str__(self) -> str:
        return self.subject

class ContactFromUser(models.Model):
    name = models.CharField(max_length = 255)
    email = models.EmailField()
    subject = models.ForeignKey(Subjects,on_delete = models.CASCADE)
    phone = models.CharField(max_length = 255)
    message = models.TextField()


    def __str__(self) -> str:
        return self.name

raisec/models.py
from django.db import models


# Create your models here.
class RaisecGroup(models.Model):
    group_name = models.CharField(max_length = 255)
    

    def __str__(self) -> str:
        return self.group_name



class RaisecQuestions(models.Model):
    raisec_category = models.ForeignKey(RaisecGroup,on_delete = models.CASCADE)
    raisec_question = models.CharField(max_length = 255)


    def __str__(self) -> str:
        return self.raisec_question







    

homepage/views.py
from multiprocessing import context
from types import NoneType
from urllib import request
from django.shortcuts import render,redirect
import pandas as pd
from scipy.sparse import csr_matrix
import numpy as np
from accounts.form import (
    SignINForm
)
from accounts.models import RaisecAnswer
# Create your views here.
from courses.models import (
    Course,
    ClusterClasses,
    AdvertUserLinks,
    CourseRattingAndComment,
    MinimumRequirement,
    UserMinimumRequirement
)
from sklearn.neighbors import NearestNeighbors
from django.contrib.auth.decorators import login_required

from raisec.models import RaisecGroup, RaisecQuestions
from .models import (
    ContactFromUser,
    ContactInfor,
    Subjects
)



def create_matrix(df):
	
	N = len(df['user'].unique())
	M = len(df['course'].unique())
	
	# Map Ids to indices
	user_mapper = dict(zip(np.unique(df["user"]), list(range(N))))
	course_mapper = dict(zip(np.unique(df["course"]), list(range(M))))
 
   
	
	# Map indices to IDs
	user_inv_mapper = dict(zip(list(range(N)), np.unique(df["user"])))
	course_inv_mapper = dict(zip(list(range(M)), np.unique(df["course"])))
	
	user_index = [user_mapper[i] for i in df['user']]
	movie_index = [course_mapper[i] for i in df['course']]

	X = csr_matrix((df["ratings"], (movie_index, user_index)), shape=(M, N))
	
	return X, user_mapper, course_mapper, user_inv_mapper, course_inv_mapper


def index(request):
    login_form = SignINForm(request.POST,None)


    all_courses = Course.objects.all()
    all_category =  ClusterClasses.objects.all()
    adverts = AdvertUserLinks.objects.all()

    context = {
        'courses' : all_courses,
        'course_category': all_category,
        'adverts' : adverts,
        'login':login_form
    }



    return render(request,'index.html',context)



def courses(request):
    all_courses = Course.objects.all()
    all_category =  ClusterClasses.objects.all()
    adverts = AdvertUserLinks.objects.all()

    context = {
        'courses' : all_courses,
        'course_category': all_category,
        'adverts' : adverts,
        'len_courses' :  len(all_courses)
    }

    return render(request,'course.html',context)


def raisec(request):
    all_raisec_group = RaisecGroup.objects.all()
    all_raisec_quiz =  RaisecQuestions.objects.all()

    context = {
        "all_raisec_group":all_raisec_group,
        "all_raisec_quiz":all_raisec_quiz


    }
    
    if request.method == "POST":
        for k in all_raisec_quiz:
           stry = f"quiz_{k.raisec_category.group_name}_{k.id}"
           t_u = request.POST.get(stry)
           if t_u is not None:
            quiz =  RaisecQuestions.objects.get(id = k.id)
            sz,created =  RaisecAnswer.objects.get_or_create(quiz = quiz ,user = request.user)
            sz.raisec_answer =  True
     
            sz.save()

        return redirect("homepage:addGrade")
    return render(request,'raisec.html',context)




def courseDetails(request,id):

    one_course =  Course.objects.get(id = id)
    all_category =  ClusterClasses.objects.all()
    course_rattings = CourseRattingAndComment.objects.filter(course = one_course)

    context = {
        'course':one_course,
         'course_category': all_category,
         'course_rattings' : course_rattings
    }

    if request.method == "POST":
        user = request.user
        
        print("request ", request.POST)
        CourseRattingAndComment.objects.create(
            user = user,
            course = one_course,
            ratings = int(request.POST.get("ratting_number")),
            comment  = request.POST.get("comment")

        )
        context['success'] = "Added Comment Successfully"
        return render(request,'course_details.html',context)
    
    return render(request,'course_details.html',context)





def recommendation(request):
    # getting raisec group
    all_answers_for_raisec = RaisecAnswer.objects.filter(user =  request.user)
    empty_list_r = []
    empty_list_i = []
    empty_list_a = []
    empty_list_s = []
    empty_list_e = []
    empty_list_c  = []

    raisec_letter = ""

    for k in all_answers_for_raisec:
        if(k.quiz.raisec_category.group_name == "R"):
            empty_list_r.append(k.quiz.raisec_category.group_name)

        elif (k.quiz.raisec_category.group_name == "I"):
            empty_list_i.append(k.quiz.raisec_category.group_name)

        elif (k.quiz.raisec_category.group_name == "A"):
            empty_list_a.append(k.quiz.raisec_category.group_name)

        elif (k.quiz.raisec_category.group_name == "S"):
            empty_list_s.append(k.quiz.raisec_category.group_name)

        elif (k.quiz.raisec_category.group_name == "E"):
            empty_list_e.append(k.quiz.raisec_category.group_name)

        elif (k.quiz.raisec_category.group_name == "C"):
            empty_list_c.append(k.quiz.raisec_category.group_name)

    new_list = [len(empty_list_r),len(empty_list_a),len(empty_list_c),len(empty_list_e),len(empty_list_i),len(empty_list_s)]
    index = new_list.index(max(new_list))
    print(index)
    if index == 0:
        raisec_letter = "R"

    elif index == 1:
        raisec_letter = "A"

    elif index == 2:
        raisec_letter = "C"

    elif index == 3:
        raisec_letter = "E"
    
    elif index == 4:
        raisec_letter = "I"
    elif index == 5:
        raisec_letter = "S"


    # get user minimum requirement 


    user_min =  UserMinimumRequirement.objects.filter(user =  request.user)
    if len(user_min) > 0:
        us =  UserMinimumRequirement.objects.get(user = request.user )
        min_requirement =  us.minimum_requirement
        print("min requirement" , min_requirement)


        print("raisec letter ", raisec_letter)
        reisec_group =  RaisecGroup.objects.filter(group_name__icontains = raisec_letter)
        if len(reisec_group) > 0:
            print("found group name")
            get_group =  RaisecGroup.objects.get(group_name = raisec_letter)

            filter_courses_recommendation = Course.objects.filter(miniumu_requirement = min_requirement,raisec_group = get_group )
            
            context = {
                "courses" : filter_courses_recommendation
            }
            
            print("filtered ",len(filter_courses_recommendation))
            return render(request,'recommendation.html',context)

    


    
   
    # df = pd.DataFrame(list(CourseRattingAndComment.objects.all().values('user', 'course', 'ratings')))
    # print("pandas df",df)
    # X, user_mapper, course_mapper, user_inv_mapper, course_inv_mapper = create_matrix(df)
    # print(user_mapper)

    # def find_similar_movies(course_id, X, k, metric='cosine', show_distance=False):
	
    #     neighbour_ids = []
        
    #     course_ind = course_mapper[course_id]
    #     course_vec = X[course_ind]
    #     k+=1
    #     kNN = NearestNeighbors(n_neighbors=k, algorithm="brute", metric=metric)
    #     kNN.fit(X)
    #     course_vec = course_vec.reshape(1,-1)
    #     print("course vec",course_vec)
    #     neighbour = kNN.kneighbors(course_vec, return_distance=show_distance)
    #     for i in range(0,k):
    #         n = neighbour.item(i)
    #         neighbour_ids.append(course_inv_mapper[n])
    #     neighbour_ids.pop(0)
    #     return neighbour_ids


    # movie_id = 1

    # similar_ids = find_similar_movies(movie_id, X, k=0.3)

    # print(similar_ids)


    

    # print(df)
    return render(request,'recommendation.html')



def addGrade(request):
    all_requirements = MinimumRequirement.objects.all()

    context = {
        'all_requirements':all_requirements
    }

    if request.method == "POST":
        grade =  request.POST.get("subject")
        get_min =  MinimumRequirement.objects.get(id =  int(grade))
 
        sv,created = UserMinimumRequirement.objects.get_or_create(user =  request.user)
        sv.minimum_requirement = get_min
        sv.save()

        return redirect("homepage:recommendation")

      
    return render(request,'enterGrade.html',context)





def contactPage(request):
    info =  ContactInfor.objects.first()
    subjects = Subjects.objects.all()

    if request.method == "POST":
        name =  request.POST.get("name")
        email =  request.POST.get("email")
        subject =  request.POST.get("subject")
        number =  request.POST.get("number")
        message =  request.POST.get("message")

        sub = Subjects.objects.get(id = int(subject))
      

        bh =  ContactFromUser.objects.create(
            name = name,
            email =  email,
            subject =  sub,
            phone = number,
            message = message


        )

        if bh is not None:
            context = {
                "message":"Saved successfully!",
                "info":info,
                "subjects":subjects
            }
            return render(request,'contact.html',context)





    context = {
         "message":"",
        "info":info,
        "subjects":subjects
    }
    return render(request,'contact.html',context)

raisec/views.py
from django.shortcuts import render

# Create your views here.

homepage/templates/contact.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="breadcumb-wrapper" data-bg-src="{% static 'assets/img/breadcumb/breadcumb-bg.jpg' %}">
    <div class="container z-index-common">
        <h1 class="breadcumb-title">Contact Us</h1>
        <ul class="breadcumb-menu">
            <li><a href="index.html">Home</a></li>
            <li>Contact Us</li>
        </ul>
    </div>
</div>
<div class="map-sec space">
    <div class="map">
        <iframe
            src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3644.7310056272386!2d89.2286059153658!3d24.00527418490799!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x39fe9b97badc6151%3A0x30b048c9fb2129bc!2sAngfuzsoft!5e0!3m2!1sen!2sbd!4v1651028958211!5m2!1sen!2sbd"
            allowfullscreen=""
            loading="lazy"
        ></iframe>
    </div>
    <div class="container">
        <div class="map-contact">
            <h3 class="border-title">Get in Touch</h3>
            <p class="mt-n1 mb-30">Have a inquiry or some feedback for us? Fill out the form below to contact our team. please contact us at hello@acadu.com.</p>
            <div class="contact-info">
                <div class="contact-info_icon"><i class="fal fa-location-dot"></i></div>
                <div class="media-body">
                    <h4 class="contact-info_title">Our Address</h4>
                    <span class="contact-info_text">{{info.address}}</span>
                </div>
            </div>
            <div class="contact-info">
                <div class="contact-info_icon"><i class="fal fa-phone"></i></div>
                <div class="media-body">
                    <h4 class="contact-info_title">Phone Number</h4>
                    <span class="contact-info_text">
                        <span>Mobile: <a href="tel:+65485965789">{{info.phone_number}}</a></span>
                    </span>
                </div>
            </div>
            <div class="contact-info">
                <div class="contact-info_icon"><i class="fal fa-clock"></i></div>
                <div class="media-body">
                    <h4 class="contact-info_title">Hours of Operation</h4>
                    <span class="contact-info_text"><span>{{info.open_hours}}</span> 
                </div>
            </div>
        </div>
    </div>
</div>
<section class="space">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-6 col-md-7 col-sm-9"><div class="title-area text-center"></div></div>
        </div>
        <div class="contact-form-wrap" data-bg-src="{% static 'assets/img/bg/contact_bg_1.png' %}">
            <span class="sub-title">Contact With Us!</span>
            <h2 class="border-title">Have Any Questions?</h2>
            {% if message %}
            
            <div class="alert alert-success" role="alert">
                {{message}}
              </div>{% endif %}
            <form action="{% url 'homepage:contact' %}" method="POST" class="contact-form">
                {% csrf_token %}
                <div class="row">
                    <div class="form-group col-md-6"><input type="text" class="form-control style3" name="name" id="name" placeholder="Enter Your Name" /> <i class="fal fa-user"></i></div>
                    <div class="form-group col-md-6"><input type="email" class="form-control style3" name="email" id="email" placeholder="Email Address" /> <i class="fal fa-envelope"></i></div>
                    <div class="form-group col-md-6">
                        <select name="subject" id="subject" class="form-select style3">
                            <option value="" disabled="disabled" selected="selected" hidden>Select Subject</option>
                            {% if subjects %}
                            {% for k in subjects  %}
                            <option value="{{k.id}}">{{k.subject}}</option>
                     
                            {% endfor %}{% endif %}
                           
                          
                        </select>
                        <i class="fal fa-chevron-down"></i>
                    </div>
                    <div class="form-group col-md-6"><input type="tel" class="form-control style3" name="number" id="number" placeholder="Phone Number" /> <i class="fal fa-phone"></i></div>
                    <div class="form-group col-12"><textarea name="message" id="message" cols="30" rows="3" class="form-control style3" placeholder="Your Message"></textarea> <i class="fal fa-comment"></i></div>
                    <div class="form-btn col-12 mt-10">
                        <button class="as-btn">Send Message<i class="fas fa-long-arrow-right ms-2"></i></button>
                    </div>
                </div>
                <p class="form-messages mb-0 mt-3"></p>
            </form>
        </div>
    </div>
</section>
<section class="" data-pos-for=".footer-wrapper" data-sec-pos="bottom-half">
    <div class="container">
        <div class="cta-wrap">
            <div class="row flex-row-reverse justify-content-between">
                <div class="col-lg-6">
                    <div class="cta-img"><img src="{% static 'assets/img/normal/cta_1_1.png' %}" alt="Image" /></div>
                </div>
                <div class="col-lg-6 align-self-center">
                    <div class="cta-content">
                        <h2 class="fs-40 fw-light text-theme mb-10">Learn From Our Platform</h2>
                        <h2 class="mb-25">That Take You Next Level</h2>
                        <a href="contact.html" class="as-btn">Register Now<i class="fas fa-arrow-right ms-2"></i></a>
                    </div>
                </div>
            </div>
            <div class="shape-mockup movingX z-index-n1" data-bottom="0%" data-left="44%"><img src="{% static 'assets/img/shape/dot_shape_1.png' %}" alt="shapes" /></div>
        </div>
    </div>
</section>

{% endblock content %}

homepage/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<section class="bg-title position-relative bg-bottom-right" data-bg-src="{% static 'assets/img/bg/bg_overlay_4.png' %}">
    <div class="img-left"><img src="{% static 'assets/img/normal/mockup_2_1.png' %}" alt="mockup"></div>
    <div class="container space z-index-common">
       <div class="row justify-content-end">
          <div class="col-xl-6">
             <div class="title-area mb-30">
               {% if request.user.is_authenticated %}
                    
                <span class="sub-title">Logged In</span>

                {% else %}
                <span class="sub-title">Log In</span>

                {% endif %}
                <h2 class="sec-title fw-medium text-white">Find Your Best Course With Us</h2>
             </div>
             <p class="mb-30 text-light">Quality technologies via fully tested methods of empowerment. Proactively disseminate web enabled best practices after cross functional expertise.</p>
             {% if request.user.is_authenticated %}
             <form class="course-form mb-2" method="POST" action="{% url 'accounts:logout' %}">
               {% csrf_token %} 
               <button type="submit" class="as-btn style3">Logout<i class="fas fa-arrow-right ms-2"></i> </button>
             </form>
             
   
             {% else %}
             <form class="course-form mb-2" method="POST" action="{% url 'accounts:signIn' %}">
               {% csrf_token %} 
               <div class="row">
                  <div class="col-md-6 form-group">
                     {{login.username}}
                  </div>
                  <div class="col-md-6 form-group">
                     {{login.password}}
                  </div>
               </div>
               <button type="submit"  class="as-btn style3">Login<i class="fas fa-arrow-right ms-2"></i></a>
            </form>
           
             {% endif %}
            
            
          
          </div>
       </div>
    </div>
 </section>

 <section class="space">
    <div class="container">
       <div class="title-area text-center text-md-start">
          <span class="sub-title">Featured Courses</span>
          <h2 class="sec-title fw-medium">Explore Top Categories</h2>
       </div>
       <div class="row gy-50">
          <div class="col-sm-6 col-xl-4">
             <div class="category-card">
                <div class="category-card_icon"><img src="{% static 'assets/img/icon/category_1_1.svg' %}" alt="icon"></div>
                <div class="category-card_content">
                   <h3 class="category-card_title"><a href="course.html">Web Development</a></h3>
                   <p class="category-card_text">Globally maintain magnetic process with model foster data after ubiuitous architectures.</p>
                   <a href="course.html" class="link-btn">Learn More<i class="fas fa-arrow-right"></i></a>
                </div>
             </div>
          </div>
          <div class="col-sm-6 col-xl-4">
             <div class="category-card">
                <div class="category-card_icon"><img src="{% static 'assets/img/icon/category_1_2.svg' %}" alt="icon"></div>
                <div class="category-card_content">
                   <h3 class="category-card_title"><a href="course.html">Digital Marketing</a></h3>
                   <p class="category-card_text">Ubiuitos maintain magnetic process with model foster data after architectures ubiuitous.</p>
                   <a href="course.html" class="link-btn">Learn More<i class="fas fa-arrow-right"></i></a>
                </div>
             </div>
          </div>
          <div class="col-sm-6 col-xl-4">
             <div class="category-card">
                <div class="category-card_icon"><img src="{% static 'assets/img/icon/category_1_3.svg' %}" alt="icon"></div>
                <div class="category-card_content">
                   <h3 class="category-card_title"><a href="course.html">UI/UX Design</a></h3>
                   <p class="category-card_text">Magnetic maintain Globally process with model architectures data after ubiuitous foster.</p>
                   <a href="course.html" class="link-btn">Learn More<i class="fas fa-arrow-right"></i></a>
                </div>
             </div>
          </div>
          <div class="col-sm-6 col-xl-4">
             <div class="category-card">
                <div class="category-card_icon"><img src="{% static  'assets/img/icon/category_1_4.svg' %}" alt="icon"></div>
                <div class="category-card_content">
                   <h3 class="category-card_title"><a href="course.html">Finance Managment</a></h3>
                   <p class="category-card_text">Genious maintain magnetic process with model foster data after ubiuitous Previoiuslyws.</p>
                   <a href="course.html" class="link-btn">Learn More<i class="fas fa-arrow-right"></i></a>
                </div>
             </div>
          </div>
          <div class="col-sm-6 col-xl-4">
             <div class="category-card">
                <div class="category-card_icon"><img src="{% static 'assets/img/icon/category_1_5.svg' %}" alt="icon"></div>
                <div class="category-card_content">
                   <h3 class="category-card_title"><a href="course.html">Graphic Design</a></h3>
                   <p class="category-card_text">Getting maintain magnetic process with model foster data after ubiuitous architectures.</p>
                   <a href="course.html" class="link-btn">Learn More<i class="fas fa-arrow-right"></i></a>
                </div>
             </div>
          </div>
          <div class="col-sm-6 col-xl-4">
             <div class="category-card">
                <div class="category-card_icon"><img src="{% static 'assets/img/icon/category_1_6.svg' %}" alt="icon"></div>
                <div class="category-card_content">
                   <h3 class="category-card_title"><a href="course.html">Product Marketing</a></h3>
                   <p class="category-card_text">Startup maintain magnetic process with model foster data after architectures ubiuitous.</p>
                   <a href="course.html" class="link-btn">Learn More<i class="fas fa-arrow-right"></i></a>
                </div>
             </div>
          </div>
       </div>
    </div>
 </section>
 <div class="space-bottom about-sec bg-bottom-right" data-bg-src="{% static 'assets/img/bg/about_bg_1.jpg' %}">
    <div class="container">
       <div class="row">
          <div class="col-xl-4 mb-40 mb-xl-0">
             <div class="img-box3"><img class="w-100" src="{% static 'assets/img/normal/about_2_1.jpg' %}" alt="About"></div>
          </div>
          <div class="col-xxl-7 col-xl-8 align-self-end">
             <div class="about-content">
                <div class="title-area mb-40">
                   <span class="sub-title">More About Us</span>
                   <h2 class="fs-40 fw-medium mt-n2">We are innovative educational institution to the creation of the student</h2>
                </div>
                <p class="mt-n2 mb-30 mb-xl-5">Compellingly procrastinate equity invested markets with efficient process improvements. Collaboratively actualize mission-critical partnerships with integrated portals. Authoritatively optimize low-risk high-yield metrics and plug-and-play potentialities.</p>
                <div class="counter-grid-wrap">
                   <div class="counter-grid">
                      <div class="counter-grid_icon"><img src="{% static 'assets/img/icon/counter_1_1.svg' %}" alt="icon"></div>
                      <div class="counter-grid_content">
                         <h3 class="counter-grid_number"><span class="counter-number">350</span></h3>
                         <span class="counter-grid_text">FINISHED WEBINARS</span>
                      </div>
                   </div>
                   <div class="counter-grid">
                      <div class="counter-grid_icon"><img src="{% static 'assets/img/icon/counter_1_2.svg' %}" alt="icon"></div>
                      <div class="counter-grid_content">
                         <h3 class="counter-grid_number"><span class="counter-number">100</span>%</h3>
                         <span class="counter-grid_text">SATISFACTION RATE</span>
                      </div>
                   </div>
                   <div class="counter-grid">
                      <div class="counter-grid_icon"><img src="{% static 'assets/img/icon/counter_1_3.svg' %}" alt="icon"></div>
                      <div class="counter-grid_content">
                         <h3 class="counter-grid_number"><span class="counter-number">656</span></h3>
                         <span class="counter-grid_text">ONLINE SESSIONS</span>
                      </div>
                   </div>
                </div>
             </div>
          </div>
       </div>
    </div>
 </div>

 <section class="space bg-smoke">
    <div class="container">
       <div class="title-area text-center">
          <span class="sub-title">Popular Courses</span>
          <h2 class="sec-title fw-medium">Our Popular Courses</h2>
       </div>
       <div class="tab-menu1 filter-menu-active">

         <button data-filter="*" class="filter-btn active">All Categories</button>
         
         {% if course_category %}
         {% for k in course_category %}
         <button data-filter=".cat{{k.id}}" class="filter-btn">{{k.category_name}}</button>
         {% endfor %}
         {% endif %}
            
         
      </div>


      {% if courses %}
      {% for u in  courses %}
      <div class="row gy-4 filter-active">
         <div class="col-md-6 col-xl-4 filter-item cat{{u.category_name.id}}">
            <div class="course-box style2">
               <div class="course-img"><img  height="200"  width="240" src="{{u.course_image.url}}" alt="course"> <span class="tag">{{u.university}}</span></div>
               <div class="course-content">
                  <h3 class="course-title"><a href="course-details.html">{{u.course_title}}</a></h3>
                  <div class="course-author">
                    
                     <div class="course-rating">
                        {% if u.ratting_percentage < 30 %}

                        <div class="star-rating" role="img" aria-label="Rated 1.00 out of 5"><span style="width:{{u.ratting_percentage}}%">Rated <strong class="rating">1.00</strong> out of 5</span></div>
                        (2.00)
                     </div>

                     {% elif  u.ratting_percentage >  40 and  u.ratting_percentage < 70 %}

                     <div class="star-rating" role="img" aria-label="Rated 3.00 out of 5"><span style="width:{{u.ratting_percentage}}%">Rated <strong class="rating">3.00</strong> out of 5</span></div>
                     (3.00)
                  </div>

                  {% elif  u.ratting_percentage >  71 and  u.ratting_percentage < 95 %}

                  <div class="star-rating" role="img" aria-label="Rated 4.00 out of 5"><span style="width:{{u.ratting_percentage}}%">Rated <strong class="rating">4.00</strong> out of 5</span></div>
                  (4.00)
               </div>

               {% elif  u.ratting_percentage  == 95 %}

               <div class="star-rating" role="img" aria-label="Rated 5.00 out of 5"><span style="width:{{u.ratting_percentage}}%">Rated <strong class="rating">5.00</strong> out of 5</span></div>
               (5.00)
            </div>
                        {% endif %}
                       
                  </div>
  
               </div>
            </div>
         </div>
       
      
      </div>
      {% endfor %}
      {% endif %}
     
    </div>
 </section>






 <div class="bg-smoke" data-pos-for=".footer-wrapper" data-sec-pos="bottom-half">
    <div class="container as-container3 z-index-common">
       <div class="row gx-10 as-carousel" data-slide-show="6" data-lg-slide-show="5" data-md-slide-show="4" data-sm-slide-show="3" data-xs-slide-show="2">
          
         {% if adverts %}
         {% for h in adverts  %}
         <div class="col-auto">
            <div class="insta-box"><img src="{{h.user_image.url}}" alt="Instagram"> <a target="_blank" href="{{h.ig_link}}" class="icon-btn"><i class="fa-brands fa-instagram"></i></a></div>
         </div>
         {% endfor %}
         {% endif %}
   
       </div>
    </div>
 </div>


{% endblock content %}